let answers =
    [
        '',
        'And in that regard, as well as in other regards, it stands as an important contribution.',
        'Some people regraded this as eyewash whereas some other people asked for the status of their complaints and actions taken.',
        'It is hard to observe the reaction of the corrector.',
        'This is interesting in parliament.',
        'Climate change is a fierce phenomenon concentrated by scientists.',
        'They have struggled since last year to make their services pay.',
        'The glimpse of something is an enormously rewarding experience.',
        'When workers ask for higher wages, the company raises its prices.',
        'It is really a comprehensive program that covers both theory and practice.',
        'I thought we would meet in the small meeting room.',
        'A party is thrown in the small meeting room.',
        'You need to hand in the essay next semester.',
        'Human being compete with other things for resources and spaces.',
        'Scientific beneficiary to space exploration is frequently questioned.',
        'Listening is the key skill to succeed to this course.',
        'Peer group pressure has a great effect on young people.',
        'Evaluation form will be reviewed by university personnel.',
        'Government reforms have been proposed at all levels.',
        'The earth\'s atmosphere is mostly composed of nitrogen and oxygen.',
        'Many toxins originate from plants or animals.',
        'Below the heating controls in the middle is a small round plastic button.',
        'The whole point of the project was to look at the norm not the exception.',
        'They have both grown up in the rural areas and dislike the urban life.',
        'These have also been found to contribute to the death of many marine animals.',
        'You are trained to be a special journalist.',
        'While reconcile is desirable, the basic underlying issues should must be addressed.',
        'Many birds migrated to the warmer areas for winter.',
        'The brief outline takes us to the beginning of the 20th century.',
        'The campus tour will hep you to get familiar with the teaching facilities.',
        'Freshwater creatures didn\'t appear in the paintings until the modern period.',
        'The excursion for children is very much open to debate.',
        'Daily practice can build confidence and improve skills.',
        'The key difference between courses is the kind of assessment.',
        'Textile manufacturer plays a large role in improving economies.',
        'This class will look at the structure of the essay.',
        'Consumer confidence has a direct impact on sales.',
        'Statistic results should be described in different ways depending on circumstances.',
        'A synopsis contains the most important information.',
        'Those seeking formal extension should talk to their faculties for more information.',
        'The aerial photograph were promptly registered for federal evaluation.',
        'A very basic definition for computing is counting and calculating.',
        'The theme of the issue was the estimation of the problem.',
        'Behind the garage, there is a flat car drawn by mules.',
        'Medical researchers have focused on the different treatments and diseases.',
        'Travelling by boat on the river is not possible in the winter.',
        'The photograph registration are for evaluation.',
        'The celebrated theory is still a subject of great controversy.',
        'Packaging is very important to attract the intentional buyer.',
        'Participants are initially selected from a range of foundation subjects.',
        'Economic problems cause a rise of unemployment.',
        'Early streams of economy in Roman republic will be examined.',
        'No more than four people are allowed in the lab.',
        'Overcrowding and poor sanitation affected the lives of the majority of the population.',
        'That brief outline takes us to the beginning of the 20th century.',
        'If you seek for further extension, contact your faculty for more information.',
        'Those students seeking formal extension should talk to their faculties for more information.',
        'Those students applying for extension should contact their faculty for information.',
        'Submission of your group assignment must be issued punctually by one of your group members.',
        'When bad drove out good, the local workers were more difficult than their competitors.',
        'All of your dissertations must be submitted by the form.',
        'The qualification will be assessed by using a criterion reference to approach.',
        'The meeting has some structure overlaps.',
        'Rivers provide habitats and migration places for many aquatic species.',
        'The time of the math lecture has been changed to ten thirty.',
        'Final year business students have to write a five thousand word essay on market trends.',
        'Interim grades will be posted on the board outside the student lounge.',
        'Our group is going to meet tomorrow in the library conference room.',
        'The first assignment will be due on the 14th of September.',
        'There was no correlation between the drugs used and cure rates.',
        'The university library has most of the necessary books.',
        'You are required to complete your research paper by next Monday.',
        'Your thesis should have a fairly limited scope.',
        'The coffee house has special student discounts throughout the week.',
        'All writers, consciously or unconsciously represent their own culture.',
        'Student identification cards will be issued by today or tomorrow.',
        'It is important to allocate your time wisely when revising.',
        'Leading companies have changed their policies after reports were released.',
        'Please remember to bring a highlighter to class next Wednesday.',
        'This slide shows that there is minimal growth.',
        'Competition for the places in this course is fierce.',
        'University departments should carefully monitor articles and publications by faculty.',
        'Today\'s lecture material will be included in the next assessment.',
        'The toughest part of research for postgraduate students is funding.',
        'Relevant materials are reserved in the library.',
        'We support the research on problems related to tropical cyclone dynamics and forecasting.',
        'The curriculum is described in the course syllabus.',
        'Conferences ought to be scheduled two weeks in advance.',
        'Reference materials are on hold at the library reference desk.',
        'Career opportunities in this field are quite limited.',
        'The schedule allows plenty of time for independent study.',
        'The campus tour runs daily during summer for prospective students.',
        'Assignments should be submitted to the department before the deadline.',
        'The history of the movement was recorded by several writers.',
        'Most theories are quite similar but a few critics disagree.',
        'The importance of the event was not yet fully understood.',
        'Avoid confusing the cause and effect of these changes.',
        'Some of the features are part of previous research.',
        'The dining hall will undergo renovations during the fall break.',
        'The solar energy department is highly regarded worldwide.',
        'Teaching assistants will receive a monthly stipend for housing.',
        'The most important process of farming is weeding.',
        'Review all materials before drawing your conclusion.',
        'Tribes worked with each other to build monolithic statues.',
        'There was not enough evidence to support these recommendations.',
        'Presidential elections are held once every four years.',
        'Expert believe that industrial development will help the economy.',
        'All staff must leave form the fire hydrant exit.',
        'Your task is to create demand for the product.',
        'The paper challenged the previously accepted theories.',
        'Student concession cards need to be obtained by completing an application form.',
        'Politics is not usually a safe topic of conversation.',
        'The scientists now study a wide variety of atmospheric processes.',
        'Heavy rain will fall throughout the country next week.',
        'Students have the option to live in college residencies or apartments.',
        'Your summary should be as clear and concise as possible.',
        'This guys is qualified to lead the groups into the mountain.',
        'The company needs to polish its image.',
        'There is a need for constructive dialogue between leaders.',
        'You can contact all your tutors by email.',
        'Relative humidity is the amount of moisture that the air can hold.',
        'The schedule allows plenty of time for individual study.',
        'Undergraduate students may participate in specific stages within the program.',
        'Our class is divided into two groups.',
        'You come with me and the other stay here.',
        'Observers waited nervously and held their breath for the concert.',
        'The decision was made with the support several faculty members.',
        'The nearest automatic teller is in front of the anatomy labs.',
        'The final year will consist of four tort courses and one project.',
        'He started his tutorial presentation right on time.',
        'Newspapers are supported primarily by the sale of advertising space.',
        'The cart carries a single object.',
        'There will be a conference here summer on using the web for academic research.',
        'The university has a world-renowned school of archaeology.',
        'Successful applicants will work with a large team of researchers.',
        'You must submit your assignments by next Friday at the latest.',
        'This module of work is more of a compositional style.',
        'The commission of funds supported among authorities has raised an argument.',
        'A number of students have volunteer jobs.',
        'Most of the features are part of the previous system.',
        'It is hard to anticipate all their actions.',
        'The application process is longer than expected.',
        'The key findings seemed to contradict our initial hypothesis.',
        'Writing an essay is easy once the research is finished.',
        'The university officer will help you locate housing and transportation.',
        'They were struggling last year to make their payments.',
        'Most critics agreed with the new theory, but a few disagreed.',
        'The results of the experiment are reported in the table below.',
        'Laws protect consumer rights and help to avoid market problems.',
        'The evaluation form will be reviewed by university personnel.',
        'Nurses specialize in clinical work and management.',
        'Sales figures for last year were better than expected.',
        'Artists played their own role as critics of culture.',
        'The first assignment is due on the fourteenth of September.',
        'The new product failed due to a lack of demand.',
        'The following economic lectures will be cancelled.',
        'The economic books are up the back, on the left.',
        'The toughest part of public transport is funding.',
        'The essay will be published once the research is finished.',
        'If you are not sure, phone student services for help.',
        'The coffee house menu featured coffee, sandwiches and toast.',
        'We cannot consider increasing the price at this stage.',
        'Behind the garage is a secret storage room.',
        'Climate change is being acknowledged by many scientists.',
        'A person\'s education level is closely related to their economic background.',
        'Everyone must evacuate the premises during the fire drill.',
        'You are required to submit your assignment by Friday.',
        'Our professor is hosting the economic development conference next week.',
        'Animals raised in captivity behave differently from their wild counterparts.',
        'If it helps to take notes in order to concentrate, please do so.',
        'The schedule allows a lot of time for independent study.',
        'To achieve full marks, an appropriate bibliography is required.',
        'Materials and resources are on hold at the library\'s front desk.',
        'Neurons are principally involved in chemical processes.',
        'The sociology department is highly regarded worldwide.',
        'When workers ask for an increase in wages, the company raises its prices.',
        'Why has the project been delayed for so long.',
        'I thought we would meet in the small meeting room.',
        'It is vital that you acknowledge all your sources.',
        'Most teaching staff make their lecture notes available online.',
        'Higher numbers of patients were infected than during previous outbreaks of illness.',
        'Inflation affects the demand, pricing and consumption of most products.',
        'Before submitting your assignment, your advisor must approve your application.',
        'There is a strict eligibility criteria to undertake background speaker studies.',
        'She received a scholarship from the state university.',
        'Try to work with each other to build up a sense of cooperation and team spirit.',
        'The technician left the new microscope in the biology lab.',
        'The thief visited the homes of several people every day.',
        'Preparation is important to avoid mishaps in the lab.',
        'Your agent will collect commission for each house they sell.',
        'Students were instructed to stand in a straight line outside of the classroom.',
        'Please note that the college laboratory will be closed for cleaning next week.',
        'Upgrading manufacturing systems can increase efficiency.',
        'Control systems in manufacturing require a high level of accuracy.',
        'We need to hand in the essay by next week.',
        'Public perception about biotechnology is crucial for developing scientific consensus.',
        'Identity theft happens to thousands of people every year.',
        'The commissioner will collect fines for the sovereignty.',
        'The findings of researchers are focused on the causes of diseases and treatments.',
        'The software companies design and create new products.',
        'Let me know if anybody struggles in the lab.',
        'Please make sure you have collected all the necessary materials.',
        'It is absolutely vital to allocate your resources.',
        'When met with high potential risks, companies will raise their prices.',
        'Students were instructed to submit their assignments by Friday.',
        'Americans have progressively found the growth in quantitative terms.',
        'The island is located at the north end of the bay.',
        'The report contains the most important information.',
        'Water taps on the campus will discourage the frequent use of plastic bottles.',
        'The early works of this research are more experimental.',
        'A recent article shows a number of interesting experiments.',
        'You should include these two pictures from the lecture in your assignment.',
        'Eight groups need to submit the outlines of their projects to their tutors.',
        'The early work is more philosophical rather than experimental.',
        'The author\'s previous works are more theoretical and less experimental.',
        'The massive accumulation of data is converted into a communicable argument.',
        'The theory has a great degree of controversy.',
        'The theme of the work requires a demure compensational style.',
        'Organization plays an important role in academic literature.',
        'The advertisement for children is open to much debate.',
        'The effect of advertising is open to much debate.',
        'Article numbers are collected through interesting experiments.',
        'Mutually exclusive events are neither complementary nor opposing.',
        'To gain full marks, an appropriate bibliography is required.',
        'Climate change is becoming an acceptable phenomenon amongst a group of reputable scientists.',
        'You can find a lot more information on the university website.',
        'Companies want to protect their brand from negative comments.',
        'Books for children often contain many bits of illustration.',
        'Before completing the exercise, you need to read the remaining chapters.',
        'Attracting skilled workers to the city with expensive housing is hard.',
        'An ancient text may hold secrets which were lost centuries ago.',
        'Agenda items should be submitted by the end of the day.',
        'Affordable housing is an important issue for all members of society.',
        'Rising sales figures means a rise in demand.',
        'Some people regarded it as care, while others regarded it as recklessness.',
        'Remember, the prestigious selection has strict eligibility criteria.',
        'Remember, the gifts purchased by children should have a striped character.'
    ];


export default answers;


